version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "uvicorn"
      - "srcs.web.app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
    volumes:
      - "./web:/app/web"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONIOENCODING=UTF-8
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
