# Your github organization on witch you want to attache your self-hosted runners
github_organization: "sclanga-devl"

# Cloud nine connection infos
cloud_nine_region: "Europe"
cloud_nine_tenant: "erwan.bernard@scality.com"

# The python module, used for configuration
# example:
#  'runners_manager.settings.settings_local'
python_config: 'backend.settings.settings_local'

# Represent the infos about each group of runners
# Define by:
#  - There openstack Flavor and image name
#  - The quantity allowed to spawn at the same time
#  - The tags use by github actions
# Example:
#  runner_pool:
#    - flavor: 'm1.small'
#      image: 'CentOS 7 (PVHVM)'
#      quantity:
#        min: 2
#        max: 4
#      tags:
#        - centos7
#        - small
runner_pool:
  - flavor: 'm1.small'
    image: 'CentOS 7 (PVHVM)'
    quantity:
      min: 2
      max: 4
    tags:
      - centos7
      - small

# If the number of runners is greater than `min`
# after x min / hours it will delete them to return to min number
extra_runner_timer:
  minutes: 10
  hours: 0

# The runner will be killed if it isn't available after this timer
timeout_runner_timer:
  minutes: 15
  hours: 0

# Define the credentials to connect your redis database
redis:
  host: redis
  port: 6379
